#ifdef RD_SHADER_OPCODE

RD_SHADER_OPCODE(NOP,		 0 | RD_SHADER_0_OPERANDS)	// no op
RD_SHADER_OPCODE(CALL,		 1 | RD_SHADER_0_OPERANDS)	// call subroutine
RD_SHADER_OPCODE(RET,		 2 | RD_SHADER_0_OPERANDS)	// return from subroutine
RD_SHADER_OPCODE(ADD,		 3 | RD_SHADER_2_OPERANDS)	// addition
RD_SHADER_OPCODE(CMP,		 4 | RD_SHADER_3_OPERANDS)	// compare
RD_SHADER_OPCODE(CND,		 5 | RD_SHADER_3_OPERANDS)	// condition
RD_SHADER_OPCODE(COS,		 6 | RD_SHADER_3_OPERANDS)	// condition
RD_SHADER_OPCODE(DIV,		 7 | RD_SHADER_2_OPERANDS)	// division
RD_SHADER_OPCODE(DP2,		 8 | RD_SHADER_2_OPERANDS)	// dot2
RD_SHADER_OPCODE(DP3,		 9 | RD_SHADER_2_OPERANDS)	// dot3
RD_SHADER_OPCODE(DP4,		10 | RD_SHADER_2_OPERANDS)	// dot4
RD_SHADER_OPCODE(EXP2,		11 | RD_SHADER_1_OPERANDS)	// base 2 exponential
RD_SHADER_OPCODE(FRC,		12 | RD_SHADER_1_OPERANDS)	// fractional
RD_SHADER_OPCODE(LOG2,		13 | RD_SHADER_1_OPERANDS)	// base 2 logarithm
RD_SHADER_OPCODE(MAD,		14 | RD_SHADER_3_OPERANDS)	// multiply add
RD_SHADER_OPCODE(MAX,		15 | RD_SHADER_2_OPERANDS)	// maximum 2
RD_SHADER_OPCODE(MIN,		16 | RD_SHADER_2_OPERANDS)	// minimum 2
RD_SHADER_OPCODE(MOV,		17 | RD_SHADER_1_OPERANDS)	// move
RD_SHADER_OPCODE(MUL,		18 | RD_SHADER_2_OPERANDS)	// multiply
RD_SHADER_OPCODE(POM,		19 | RD_SHADER_3_OPERANDS)	// parallax
RD_SHADER_OPCODE(RCP,		20 | RD_SHADER_1_OPERANDS)	// reciprocal
RD_SHADER_OPCODE(RSQRT,		21 | RD_SHADER_1_OPERANDS)	// reciprocal square root
RD_SHADER_OPCODE(SIN,		22 | RD_SHADER_1_OPERANDS)	// sine
RD_SHADER_OPCODE(TEX,		23 | RD_SHADER_2_OPERANDS)	// texture
RD_SHADER_OPCODE(TEXLOD,	24 | RD_SHADER_2_OPERANDS)	// texture lod
RD_SHADER_OPCODE(TEXADD,	25 | RD_SHADER_3_OPERANDS)	// texture + add
RD_SHADER_OPCODE(TEXINFO,	26 | RD_SHADER_2_OPERANDS)  // texture info (size, mips)

#endif
