#ifdef RD_SHADER_OPCODE

RD_SHADER_OPCODE(NOP,		 0 | RD_SHADER_0_OPERANDS)	// no op
RD_SHADER_OPCODE(CALL,		 1 | RD_SHADER_0_OPERANDS)	// call subroutine
RD_SHADER_OPCODE(RET,		 2 | RD_SHADER_0_OPERANDS)	// return from subroutine
RD_SHADER_OPCODE(REP,        3 | RD_SHADER_0_OPERANDS)	// begin counted loop, count from src0
RD_SHADER_OPCODE(ENDREP,     4 | RD_SHADER_0_OPERANDS)	// end counted loop, body-start PC in addr field
RD_SHADER_OPCODE(ADD,		 5 | RD_SHADER_2_OPERANDS)	// addition
RD_SHADER_OPCODE(CMP,		 6 | RD_SHADER_3_OPERANDS)	// compare
RD_SHADER_OPCODE(CND,		 7 | RD_SHADER_3_OPERANDS)	// condition
RD_SHADER_OPCODE(COS,		 8 | RD_SHADER_1_OPERANDS)	// cosine
RD_SHADER_OPCODE(DP2,		 9 | RD_SHADER_2_OPERANDS)	// dot2
RD_SHADER_OPCODE(DP3,		10 | RD_SHADER_2_OPERANDS)	// dot3
RD_SHADER_OPCODE(DP4,		11 | RD_SHADER_2_OPERANDS)	// dot4
RD_SHADER_OPCODE(EXP2,		12 | RD_SHADER_1_OPERANDS)	// base 2 exponential
RD_SHADER_OPCODE(FRC,		13 | RD_SHADER_1_OPERANDS)	// fractional
RD_SHADER_OPCODE(LOG2,		14 | RD_SHADER_1_OPERANDS)	// base 2 logarithm
RD_SHADER_OPCODE(MAD,		15 | RD_SHADER_3_OPERANDS)	// multiply add
RD_SHADER_OPCODE(MAX,		16 | RD_SHADER_2_OPERANDS)	// maximum 2
RD_SHADER_OPCODE(MIN,		17 | RD_SHADER_2_OPERANDS)	// minimum 2
RD_SHADER_OPCODE(MOV,		18 | RD_SHADER_1_OPERANDS)	// move
RD_SHADER_OPCODE(MUL,		19 | RD_SHADER_2_OPERANDS)	// multiply
RD_SHADER_OPCODE(POW,       20 | RD_SHADER_2_OPERANDS)  // pow
RD_SHADER_OPCODE(POM,		21 | RD_SHADER_3_OPERANDS)	// parallax
RD_SHADER_OPCODE(RSQRT,		22 | RD_SHADER_1_OPERANDS)	// reciprocal square root
RD_SHADER_OPCODE(SIN,		23 | RD_SHADER_1_OPERANDS)	// sine
RD_SHADER_OPCODE(TEX,		24 | RD_SHADER_2_OPERANDS)	// texture
RD_SHADER_OPCODE(TEXLOD,	25 | RD_SHADER_2_OPERANDS)	// texture lod
RD_SHADER_OPCODE(TEXADD,	26 | RD_SHADER_3_OPERANDS)	// texture + add
RD_SHADER_OPCODE(TEXINFO,	27 | RD_SHADER_2_OPERANDS)  // texture info (size, mips)
RD_SHADER_OPCODE(TEXKILL,   28 | RD_SHADER_1_OPERANDS)  // discard if src.a < threshold, forces WORLD_STAGE_COLOR_ALPHATEST

#endif
